---
- name: Nginx Install
  hosts: web
  become: true
  gather_facts: true

  tasks:
    - name: EC2 Nginx install
      yum:
        name: nginx
        state: present 

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started 


        
this is a playbook.yml:
---
- name: Nginx Install
  hosts: web
  become: true
  gather_facts: true
  tasks:
    - name: EC2 Nginx install
      yum:
        name: nginx
        state: present 
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started 


    - name: EC2 JDK install
      yum:
        name: java-11-openjdk
        state: present
    - name: Ensure JDK is installed
      command: java -version
      register: java_version
      changed_when: false
